baseURL = "https://tachunwu.github.io/emergen-c/"
languageCode = "en-us"
title = "EMERGEN-C"
theme="archie"
copyright = "© Tachun Wu"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

paginate=100 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Distributed Systems, Databases, Art, Machine Learning, Design, Cannabis, Bangkok"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/tachunwu"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/athulcajay/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

# Main menu Items

# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

[[menu.main]]
name = "Dispensary"
url = "/dispensary"
weight = 2

[[menu.main]]
name = "Landscape"
url = "/landscape"
weight = 3

[[menu.main]]
name = "CockroachDB"
url = "/cockroachdb"
weight = 4

[[menu.main]]
name = "NATS"
url = "/nats"
weight = 5

[[menu.main]]
name = "Tinygrad"
url = "/tinygrad"
weight = 6

[[menu.main]]
name = "About"
url = "/about"
weight = 7

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 8